## https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html#image
image: clojure:latest

pages:
  stage: deploy
  tags:
  - docker
  script:
  - lein codox
  artifacts:
    paths:
    - public
