## https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html#image

pages:
  stage: deploy
  tags:
  - shell
  
  before_script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  
  script:
  - lein codox
  artifacts:
    paths:
    - public
