## https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html#image

stages:
  - deploy

.page_cache: &page_cache
  variables:
    GIT_STRATEGY: none # no need sources, everything comes from cache or artifacts
  cache:
    key: "$CI_DEFAULT_BRANCH"
    paths:
      - public/

pages:
  stage: deploy
  tags:
    - docker
  #<<: *page_cache
  image: clojure:openjdk-11-lein-slim-buster
  before_script:
    - apt update && apt install -y git

  script:
    - lein codox
  artifacts:
    paths:
      - public/
